H2W_mvc/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using System.Net;
using H2W_mvc.Models;
using H2W_lib;

namespace H2W_mvc.Controllers
{
    public class FormsController : Controller
    {
        //
        // GET: /Forms/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ThankYou()
        {
            return View();
        }


        public ActionResult LinearMotorsWorksheet()
        {
            LinearMotorsWorksheet vm = new LinearMotorsWorksheet();
            return View(vm);
        }
        [HttpPost]
        public ActionResult LinearMotorsWorksheet(LinearMotorsWorksheet vm)
        {
            if (ModelState.IsValid)
            {
                string st = "<strong>Positioning Stage</strong><br><br>";
                st += "From: " + vm.FullName + "<br>";
                st += "Company: " + vm.Company + "<br>";
                st += "Phone: " + vm.Phone + "<br>";
                st += "Email: " + vm.Email + "<br><br>";
                st += "What force is required?  " + vm.Quest1 + " " + vm.Quest1ddl + "<br>";
                st += "What is the weight of your payload? " + vm.Quest2 + " " + vm.Quest2ddl + "<br>";
                st += "What is the required acceleration? " + vm.Quest3 + "[g's]<br>";
                st += "What is the time required to complete the travel? " + vm.Quest4 + "[sec]<br>";
                st += "What is the total required travel? " + vm.Quest5 + " " + vm.Quest5ddl + "<br>";
                st += "What is the duty cycle for force or acceleration required? " + vm.Quest6 + "[%]<br>";
                st += "What is the required velocity? " + vm.Quest7 + " " + vm.Quest7ddl + "<br>";
                st += "Open or closed loop operation? " + vm.Quest8 + "<br>";
                st += "Horizontal or vertical orientation? " + vm.Quest12 + "<br>";
                st += "Does your motor require bearings? " + vm.Quest9 + "<br>";
                st += "What are the ambient conditions of the application? " + vm.Quest10 + "<br>";
                st += "What is the available power source? " + vm.Quest11 + " " + vm.Quest11ddl + "<br>";
                st += "Comments: " + vm.Comments + "<br>";

                Utility.SendFormEmail(st);

                return RedirectToAction("ThankYou");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult RotaryMotorsWorksheet()
        {
            RotaryMotorsWorksheet vm = new RotaryMotorsWorksheet();
            return View(vm);
        }
        [HttpPost]
        public ActionResult RotaryMotorsWorksheet(RotaryMotorsWorksheet vm)
        {
            if (ModelState.IsValid)
            {
                string st = "<strong>Rotary Motors Worksheet</strong><br><br>";
                st += "From: " + vm.FullName + "<br>";
                st += "Company: " + vm.Company + "<br>";
                st += "Phone: " + vm.Phone + "<br>";
                st += "Email: " + vm.Email + "<br><br>";
                st += "What is your total angular excursion? " + vm.Quest1 + " [degrees]<br>";
                st += "What is the inertia of your payload? " + vm.Quest2 + " [oz-in-sec]<br>";
                st += "What is the required speed? " + vm.Quest3 + " [rpm]<br>";
                st += "What is the time required to complete the rotation? " + vm.Quest4 + " [sec]<br>";
                st += "What is the required angular acceleration? " + vm.Quest5 + " [rad/sec<sup>2</sup>]<br>";
                st += "What continuous torque is required? " + vm.Quest6 + " "+ vm.Quest6ddl + "<br>";
                st += "What is the peak torque is required? " + vm.Quest7 + " " + vm.Quest7ddl + "<br>";
                st += "What is the duty cycle for torque or acceleration required? " + vm.Quest8 + " %<br>";
                st += "Is position feedback required?  " + vm.Quest9 + "<br>";
                st += "What is the required accuracy?  " + vm.Quest10 + " " + vm.Quest10ddl + "<br>";
                st += "What is the required repeatability? " + vm.Quest11 + " " + vm.Quest11ddl + "<br>";
                st += "What are the ambient conditions of the application?  " + vm.Quest12 + " " + vm.Quest12ddl + "<br>";
                st += "What is the available continuous current (amps)?  " + vm.Quest13 + " " + vm.Quest13ddl + "<br>";

                st += "Comments: " + vm.Comments + "<br>";

                Utility.SendFormEmail(st);

                return RedirectToAction("ThankYou");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        public ActionResult PositioningStagesWorksheet()
        {
            PositioningStagesWorksheet vm = new PositioningStagesWorksheet();
            return View(vm);
        }
        [HttpPost]
        public ActionResult PositioningStagesWorksheet(PositioningStagesWorksheet vm)
        {
            if (ModelState.IsValid)
            {
                string st = "<strong>Positioning Stage</strong><br><br>";
                st += "From: " + vm.FullName + "<br>";
                st += "Company: " + vm.Company + "<br>";
                st += "Phone: " + vm.Phone + "<br>";
                st += "Email: " + vm.Email + "<br><br>";
                st += "What force is required?  " + vm.Quest1 + " " + vm.Quest1ddl + "<br>";
                st += "What is the weight of your payload? " + vm.Quest2 + " " + vm.Quest2ddl + "<br>";
                st += "What is the required acceleration? " + vm.Quest3 + "<br>";
                st += "What is the time required to complete the travel? " + vm.Quest4 + "<br>";
                st += "What is the total required travel? " + vm.Quest5 + " " + vm.Quest5ddl + "<br>";
                st += "What is the duty cycle for force or acceleration required? " + vm.Quest6 + "<br>";
                st += "What is the required velocity? " + vm.Quest7 + " " + vm.Quest7ddl + "<br>";
                st += "What is the required accuracy? " + vm.Quest8 + " " + vm.Quest8ddl + "<br>";
                st += "What is the required repeatability? " + vm.Quest9 + " " + vm.Quest9ddl + "<br>";
                st += "What is the required flatness of motion? " + vm.Quest10 + " " + vm.Quest10ddl + "<br>";
                st += "What is the required straightness of motion? " + vm.Quest11 + " " + vm.Quest12ddl + "<br>";
                st += "What are the ambient conditions for the application? " + vm.Quest13 + "<br>";
                st += "What is the available continuous current (amps)? " + vm.Quest14 + " " + vm.Quest14ddl + "<br>";
                st += "Horizontal or vertical orientation? " + vm.Quest15 + "<br>";
                st += "What are the ambient conditions of the application? " + vm.Quest16 + "<br>";

                st += "Comments: " + vm.Comments + "<br>";

                Utility.SendFormEmail(st);

                return RedirectToAction("ThankYou");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult RequestForQuoteForm(string productNo, string catID)
        {
            RequestForQuoteForm vm = new RequestForQuoteForm();
            ViewBag.productNo = HttpContext.Request.QueryString["productNo"];
            ViewBag.catID = HttpContext.Request.QueryString["cat"];
            return View(vm);
        }
        [HttpPost]
        public ActionResult RequestForQuoteForm(RequestForQuoteForm vm)
        {
            if (ModelState.IsValid)
            {
                string st = "<strong>Request for Quote Form</strong><br><br>";
                st += "From: " + vm.FullName + "<br>";
                st += "Company: " + vm.Company + "<br>";
                st += "Phone: " + vm.Phone + "<br>";
                st += "Email: " + vm.Email + "<br><br>";
                st += "Interest in Product Number: " + vm.Quest1 + "<br>";
                st += "Interested in Category: " + vm.Quest2 + "<br>";
                st += "Quantity Needed: " + vm.Quest3 + "<br><br>";
                st += "Comments: " + vm.Comments + "<br>";

                Utility.SendFormEmail(st);

                return RedirectToAction("ThankYou");
            }
            return View(vm);
        }
    }

}

H2W_mvc/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using H2W_lib;
using H2W_mvc.ViewModels;

namespace H2W_mvc
{
    public class PagesController : Controller
    {
        //Says db is already defined in the namespace... is that going to be a problem?
        H2WtechEntities db2 = new H2WtechEntities();

        public ActionResult Show(int pageid)
        {
            //ManagePageViewModel MPVM = new ManagePageViewModel(db2);
            //MPVM.BuildVM(pageid);
            //ViewBag.Title = MPVM.currentVM.textrec.section;
            //ViewBag.Description = MPVM.currentVM.textrec.section;
            //ViewBag.Keywords = MPVM.currentVM.textrec.section;

            var pagerec = (from c in db2.tblTexts where c.pageId == pageid select c).FirstOrDefault();
            string redirUrl = "../page/" + pagerec.slug;
            return RedirectPermanent(redirUrl);

            //return View(MPVM.currentVM);


        }

    }
}

H2W_mvc/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Application Worksheets";
}


<h2>Application Worksheets</h2>
<div style="height:7px; clear:both;"></div>

<div id="pageContainer">
    <img src="~/Images/appWorksheets.jpg" align="right" />
    <span style="font-size:20px;">These applications will help you find the right product, obtain help and advice from a H2W engineer, request a quote and place an order.</span>
    <br /><br />

    <span style="font-size:17px; line-height:32px;">
        <img src="~/Images/clipboard.png" style="position:relative;top:4px;" />@Html.ActionLink("Linear Motors Product Sizing Worksheet", "LinearMotorsWorksheet", "Forms")<br />
        <img src="~/Images/clipboard.png" style="position:relative;top:4px;" />@Html.ActionLink("Rotary Motors Product Sizing Worksheet", "RotaryMotorsWorksheet", "Forms")<br />
        <img src="~/Images/clipboard.png" style="position:relative;top:4px;" />@Html.ActionLink("Positioning Stages Product Sizing Worksheet", "PositioningStagesWorksheet", "Forms")<br />
        <img src="~/Images/clipboard.png" style="position:relative;top:4px;" /><a href="~/Content/Credit%20Card%20Authorization%20Form.pdf">Credit Card Authorization PDF</a><br />
        <img src="~/Images/clipboard.png" style="position:relative;top:4px;" />@Html.ActionLink("Request for Quote Form", "RequestForQuoteForm", "Forms")<br />
    </span>
    <br />
    We'd to love to talk to you! @Html.ActionLink("Click here for our contact info.", "Show", "Pages", new { pageid = "11" }, null)
        <div style="clear:both"></div>
    
</div><!--//tabContainer-->

H2W_mvc/Views/Forms/LinearMotorsWorksheet.cshtml
@model H2W_mvc.Models.LinearMotorsWorksheet
@using H2W_mvc.Models
@{
    ViewBag.Title = "Linear Motor Worksheet";
}
<h2>Linear Motor Worksheet</h2>

@using (Html.BeginForm()) {
@Html.ValidationSummary(true)

<fieldset class="worksheetClass">

    <legend>LinearMotorsWorksheet</legend>

    <div style="height:10px;"></div>
    <div style="width:450px; float:left;">
        <div class="display-label">
             @Html.DisplayNameFor(model => model.FullName)
        </div>
        <div class="display-field">
             @Html.TextBoxFor( m => m.FullName, new { @class = "worksheetField" }) <span class="req">*</span>
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.FullName)
        </div>
        <br clear="all" />

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Company)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Company, new { @class = "worksheetField" }) <span class="req">*</span>
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Company)
        </div>
    </div>
    
    <div style="width:450px; float:left;">
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Email)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Email, new { @class = "worksheetField" }) <span class="req">*</span>
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <br clear="all" />

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Phone)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Phone, new { @class = "worksheetField" }) <span class="req">*</span>
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Phone)
        </div>
    </div>
    <br clear="all" />
    <br />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest1)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest1, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2" style="width:200px;">
         @Html.DropDownList("Quest1ddl", new SelectList(measurementTables.weight),"--select--")<span id="Quest1Alert" class="r8">&nbsp;< REQUIRED</span>
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest2)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest2, new { @class = "worksheetField2" })
    </div>
    <div id="whatEver" class="display-foot2" style="width:200px;">
         @Html.DropDownList("Quest2ddl", new SelectList(measurementTables.weight),"--select--")<span id="Quest2Alert" class="r8">&nbsp;< REQUIRED</span>
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest3)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest3, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2">
         [g's]
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest4)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest4, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2">
         [sec]
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest5)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest5, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2" style="width:200px;">
         @Html.DropDownList("Quest5ddl", new SelectList(measurementTables.length),"--select--")<span id="Quest5Alert" class="r8">&nbsp;< REQUIRED</span>
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest6)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest6, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2">
         [%]
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest7)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest7, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2" style="width:200px;">
         @Html.DropDownList("Quest7ddl", new SelectList(measurementTables.velocity),"--select--")<span id="Quest7Alert" class="r8">&nbsp;< REQUIRED</span>
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest8)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest8, new { @class = "worksheetField2" })
    </div>
    <br clear="all" />

    <div class="display-label2">
        @Html.DisplayNameFor(model => model.Quest12)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest12, new { @class = "worksheetField2" })
    </div>
    <br clear="all" />


    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest9)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest9, new { @class = "worksheetField2" })
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest10)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest10, new { @class = "worksheetField2" })
    </div>
    <br clear="all" />

    <div class="display-label2">
         @Html.DisplayNameFor(model => model.Quest11)
    </div>
    <div class="display-field2">
        @Html.TextBoxFor(model => model.Quest11, new { @class = "worksheetField2" })
    </div>
    <div class="display-foot2" style="width:200px;">
         @Html.DropDownList("Quest11ddl", new SelectList(measurementTables.power),"--select--")<span id="Quest11Alert" class="r8">&nbsp;< REQUIRED</span>
    </div>
    <br clear="all" />
    <br />

    <span style="font-size:12px;">
    Please describe to us in as much detail as possible about your application in the space provided below.
Please e-mail or fax any sketches, CAD drawings, velocity profiles, or system specifications you may have.
    </span><div style="clear:both;"></div> 
    <div class="display-field2">
        @Html.TextAreaFor(model => model.Comments, new { @class = "worksheetTextArea" })
    </div>
    <br clear="all" /><br />
    <span style="font-size:13px;">This is usually enough information to get us going with the selection process. One of our engineers will contact you directly to discuss your application in detail and determine which one of our products will best suit your requirements.</span>
    <br clear="all" /><br />
    

    <input type="submit" value="Submit Form" />

        
</fieldset>
}

<script type="text/javascript">
    $("#Quest1").keyup(function () {
        if ($("#Quest1").val().length > 0 && $('#Quest1ddl').val() == "") {
            $('#Quest1Alert').fadeIn('slow');
            $('#Quest1ddl').addClass('r9');
        } else {
            $('#Quest1ddl').removeClass('r9');
            $('#Quest1Alert').fadeOut('slow');
        }
    });

    $("#Quest2").keyup(function () {
        if ($("#Quest2").val().length > 0 && $('#Quest2ddl').val() == "") {
            $('#Quest2Alert').fadeIn('slow');
            $('#Quest2ddl').addClass('r9');
        } else {
            $('#Quest2ddl').removeClass('r9');
            $('#Quest2Alert').fadeOut('slow');
        }
    });

    $("#Quest5").keyup(function () {
        if ($("#Quest5").val().length > 0 && $('#Quest5ddl').val() == "") {
            $('#Quest5Alert').fadeIn('slow');
            $('#Quest5ddl').addClass('r9');
        } else {
            $('#Quest5ddl').removeClass('r9');
            $('#Quest5Alert').fadeOut('slow');
        }
    });

    $("#Quest7").keyup(function () {
        if ($("#Quest7").val().length > 0 && $('#Quest7ddl').val() == "") {
            $('#Quest7Alert').fadeIn('slow');
            $('#Quest7ddl').addClass('r9');
        } else {
            $('#Quest7ddl').removeClass('r9');
            $('#Quest7Alert').fadeOut('slow');
        }
    });

    $("#Quest11").keyup(function () {
        if ($("#Quest11").val().length > 0 && $('#Quest11ddl').val() == "") {
            $('#Quest11Alert').fadeIn('slow');
            $('#Quest11ddl').addClass('r9');
        } else {
            $('#Quest11ddl').removeClass('r9');
            $('#Quest11Alert').fadeOut('slow');
        }
    });




</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

H2W_mvc/Views/Forms/RequestForQuoteForm.cshtml
@model H2W_mvc.Models.RequestForQuoteForm
@{
    ViewBag.Title = "Get a fast, free, no-obligation quote from us";
}

<h2>Request For Quote</h2>

@using (Html.BeginForm()) {
@Html.ValidationSummary(true)

<fieldset class="worksheetClass">

    <legend>LinearMotorsWorksheet</legend>

    <div style="height:10px;"></div>
    <div style="width:450px; float:left;">
        <div class="display-label">
             @Html.DisplayNameFor(model => model.FullName)
        </div>
        <div class="display-field">
             @Html.TextBoxFor( m => m.FullName, new { @class = "worksheetField" })
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.FullName)
        </div>
        <br clear="all" />

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Company)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Company, new { @class = "worksheetField" })
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Company)
        </div>
    </div>
    
    <div style="width:450px; float:left;">
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Email)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Email, new { @class = "worksheetField" })
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <br clear="all" />

        <div class="display-label">
             @Html.DisplayNameFor(model => model.Phone)
        </div>
        <div class="display-field">
            @Html.TextBoxFor(model => model.Phone, new { @class = "worksheetField" })
        </div>
        <div class="display-error">
            @Html.ValidationMessageFor(m => m.Phone)
        </div>
    </div>
    <br clear="all" />
    <br />

    <div class="display-label3">
         @Html.DisplayNameFor(model => model.Quest1)
    </div>
    <div class="display-field3">
        @Html.TextBoxFor(model => model.Quest1, new { @class = "worksheetField3" })
    </div>
    <br clear="all" />

    <div class="display-label3">
         @Html.DisplayNameFor(model => model.Quest2)
    </div>
    <div class="display-field3">
        @Html.TextBoxFor(model => model.Quest2, new { @class = "worksheetField3", @value = ViewBag.catID })
    </div>
    <br clear="all" />

    <div class="display-label3">
         @Html.DisplayNameFor(model => model.Quest3)
    </div>
    <div class="display-field3">
        @Html.TextBoxFor(model => model.Quest3, new { @class = "worksheetField3" })
    </div>
    <br clear="all" />

    <br />

    <span style="font-size:12px;">
    Comments & Special Instructions:
    </span><div style="clear:both;"></div> 
    <div class="display-field2">
        @Html.TextAreaFor(model => model.Comments, new { @class = "worksheetTextArea" })
    </div>
    <br clear="all" /><br />
    <input type="submit" value="Request Quote" />

        
</fieldset>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

H2W_mvc/Views/Forms/ThankYou.cshtml
<h2>Thank You!</h2>
<div style="height:7px; clear:both;"></div>

<div id="pageContainer">
    <img src="~/Images/appWorksheets.jpg" align="right" />
    <span style="font-size:20px;">Your form was sent and a H2W specialist will be contacting you very soon.</span>
    <br />
    <div style="clear:both"></div>
</div><!--//tabContainer-->